// Copyright 2026 Carlos Escobar-Valbuena
// SPDX-License-Identifier: Apache-2.0

//! `symphony init` — scaffold a WORKFLOW.md in the current directory.

use std::path::Path;

use super::InitArgs;

const LINEAR_TEMPLATE: &str = r#"---
# Symphony WORKFLOW.md — Linear + Claude Code
# Generated by `symphony init --tracker linear`

tracker:
  kind: linear
  api_key: $LINEAR_API_KEY
  project_slug: your-project-slug     # From Linear project URL
  active_states:
    - Todo
    - In Progress
  terminal_states:
    - Done
    - Canceled
    - Duplicate
  # done_state: Done                  # Uncomment to auto-transition on success

polling:
  interval_ms: 30000

workspace:
  root: ~/symphony-workspaces/my-project

hooks:
  after_create: |
    # Clone your repo into the workspace on first creation
    gh repo clone your-org/your-repo . -- --depth 50
    git checkout -b "symphony/$SYMPHONY_ISSUE_ID"
  before_run: |
    git add -A && git stash || true
    git fetch origin main
    git rebase origin/main || git rebase --abort
    git stash pop || true
  after_run: |
    git add -A
    git commit -m "$SYMPHONY_ISSUE_ID: $SYMPHONY_ISSUE_TITLE" || true
    git push -u origin "symphony/$SYMPHONY_ISSUE_ID" --force-with-lease || true
  # pr_feedback: |
  #   # Uncomment to enable PR review comment feedback loop
  #   PR_NUM=$(gh pr view "symphony/$SYMPHONY_ISSUE_ID" --json number -q '.number' 2>/dev/null)
  #   if [ -n "$PR_NUM" ]; then
  #     gh api "repos/your-org/your-repo/pulls/$PR_NUM/comments" \
  #       --jq '.[] | "**\(.user.login)**: \(.body)"' 2>/dev/null
  #   fi
  # after_session: |
  #   # Uncomment to capture session outcome (e.g. for conversation bridge)
  #   echo "$SYMPHONY_ISSUE_ID: $SYMPHONY_SESSION_OUTCOME (tokens: $SYMPHONY_TOKENS_TOTAL)"
  timeout_ms: 180000

agent:
  max_concurrent_agents: 2
  max_turns: 3

codex:
  command: claude --dangerously-skip-permissions

server:
  port: 8080

# profile:
#   role: "senior full-stack engineer"
#   consciousness: governed        # baseline | governed | autonomous
#   skills: [agentic-control-kernel, knowledge-graph-memory]
#   control_profile: governed      # baseline | governed | autonomous
#   context: "This is a monorepo with strict linting. Always run make check."
---

You are a senior engineer working on {{ issue.identifier }}: {{ issue.title }}.

## Control Metalayer
1. Read CLAUDE.md and AGENTS.md for project conventions
2. If `.symphony-pr-feedback.md` exists, resolve PR comments first
3. Follow: implement → test → lint → verify

{% if issue.description %}
## Issue Description
{{ issue.description }}
{% endif %}

{% if issue.labels %}
## Labels
{{ issue.labels | join: ", " }}
{% endif %}

## Instructions
1. Read the project structure and understand the codebase
2. Implement the requested changes following existing patterns
3. Write or update tests for your changes
4. Ensure the code compiles and lints cleanly
5. Keep changes focused — only modify what the ticket requires

{% if attempt %}
## Retry Attempt {{ attempt }}
Check git log for prior work. Resolve `.symphony-pr-feedback.md` comments first if present.
{% endif %}
"#;

const GITHUB_TEMPLATE: &str = r#"---
# Symphony WORKFLOW.md — GitHub Issues + Claude Code
# Generated by `symphony init --tracker github`

tracker:
  kind: github
  api_key: $GITHUB_TOKEN
  project_slug: your-org/your-repo     # owner/repo format
  active_states:
    - open
  terminal_states:
    - closed
  # done_state: closed                 # Uncomment to auto-close on success

polling:
  interval_ms: 60000

workspace:
  root: ~/symphony-workspaces/my-project

hooks:
  after_create: |
    gh repo clone your-org/your-repo . -- --depth 50
    git checkout -b "symphony/$SYMPHONY_ISSUE_ID"
  before_run: |
    git add -A && git stash || true
    git fetch origin main
    git rebase origin/main || git rebase --abort
    git stash pop || true
  after_run: |
    git add -A
    git commit -m "$SYMPHONY_ISSUE_ID: $SYMPHONY_ISSUE_TITLE" || true
    git push -u origin "symphony/$SYMPHONY_ISSUE_ID" --force-with-lease || true
  # pr_feedback: |
  #   # Uncomment to enable PR review comment feedback loop
  #   PR_NUM=$(gh pr view "symphony/$SYMPHONY_ISSUE_ID" --json number -q '.number' 2>/dev/null)
  #   if [ -n "$PR_NUM" ]; then
  #     gh api "repos/your-org/your-repo/pulls/$PR_NUM/comments" \
  #       --jq '.[] | "**\(.user.login)**: \(.body)"' 2>/dev/null
  #   fi
  # after_session: |
  #   # Uncomment to capture session outcome (e.g. for conversation bridge)
  #   echo "$SYMPHONY_ISSUE_ID: $SYMPHONY_SESSION_OUTCOME (tokens: $SYMPHONY_TOKENS_TOTAL)"
  timeout_ms: 120000

agent:
  max_concurrent_agents: 3
  max_turns: 5

codex:
  command: claude --dangerously-skip-permissions

server:
  port: 8082

# profile:
#   role: "senior full-stack engineer"
#   consciousness: governed        # baseline | governed | autonomous
#   skills: []
#   control_profile: governed      # baseline | governed | autonomous
#   context: ""
---

You are working on GitHub issue {{ issue.identifier }}: {{ issue.title }}.

## Control Metalayer
1. Read CLAUDE.md and AGENTS.md for project conventions
2. If `.symphony-pr-feedback.md` exists, resolve PR comments first
3. Follow: implement → test → lint → verify

{% if issue.description %}
## Details
{{ issue.description }}
{% endif %}

{% if issue.labels %}
## Labels
{{ issue.labels | join: ", " }}
{% endif %}

Implement the fix or feature. Write tests. Follow the project's conventions.

{% if attempt %}
## Retry Attempt {{ attempt }}
Check git log for prior work. Resolve `.symphony-pr-feedback.md` comments first if present.
{% endif %}
"#;

const MARKDOWN_TEMPLATE: &str = r#"---
# Symphony WORKFLOW.md — Markdown Issues + Claude Code
# Generated by `symphony init --tracker markdown`
#
# Issues are .md files in the project_slug directory.
# Each file has YAML front matter with: id, title, state, priority, labels, blocked_by.
# No external API or credentials required.

tracker:
  kind: markdown
  api_key: unused                        # Not required for markdown tracker
  endpoint: ""                           # Optional: Lago HTTP endpoint for journaling
                                         # e.g. http://localhost:8080
                                         # Leave empty for local-only JSONL journal
  project_slug: ./tasks/                 # Directory containing issue .md files
  active_states:
    - Todo
    - In Progress
  terminal_states:
    - Done
    - Canceled
  done_state: Done                       # Auto-transition on success

polling:
  interval_ms: 10000                     # Local FS is fast, poll more frequently

workspace:
  root: ~/symphony-workspaces/my-project

hooks:
  after_create: |
    # Copy or clone your project into the workspace
    cp -r /path/to/your/project/. . || true
    git checkout -b "symphony/$SYMPHONY_ISSUE_ID" || true
  before_run: |
    git add -A && git stash || true
    git fetch origin main 2>/dev/null || true
    git rebase origin/main 2>/dev/null || git rebase --abort 2>/dev/null || true
    git stash pop || true
  after_run: |
    git add -A
    git commit -m "$SYMPHONY_ISSUE_ID: $SYMPHONY_ISSUE_TITLE" || true
  # after_session: |
  #   # Uncomment to capture session outcome (e.g. for conversation bridge)
  #   echo "$SYMPHONY_ISSUE_ID: $SYMPHONY_SESSION_OUTCOME (tokens: $SYMPHONY_TOKENS_TOTAL)"
  timeout_ms: 120000

agent:
  max_concurrent_agents: 2
  max_turns: 3

codex:
  command: claude --dangerously-skip-permissions

server:
  port: 8084

# profile:
#   role: "senior full-stack engineer"
#   consciousness: governed        # baseline | governed | autonomous
#   skills: []
#   control_profile: governed      # baseline | governed | autonomous
#   context: ""
---

You are a senior engineer working on {{ issue.identifier }}: {{ issue.title }}.

## Control Metalayer
1. Read CLAUDE.md and AGENTS.md for project conventions
2. Follow: implement → test → lint → verify

{% if issue.description %}
## Issue Description
{{ issue.description }}
{% endif %}

{% if issue.labels %}
## Labels
{{ issue.labels | join: ", " }}
{% endif %}

## Instructions
1. Read the project structure and understand the codebase
2. Implement the requested changes following existing patterns
3. Write or update tests for your changes
4. Ensure the code compiles and lints cleanly
5. Keep changes focused — only modify what the ticket requires

{% if attempt %}
## Retry Attempt {{ attempt }}
Check git log for prior work and avoid repeating failed approaches.
{% endif %}
"#;

pub fn run_init(args: &InitArgs) -> anyhow::Result<()> {
    let output_path = &args.output;

    if output_path.exists() && !args.force {
        anyhow::bail!(
            "{} already exists. Use --force to overwrite.",
            output_path.display()
        );
    }

    let template = match args.tracker.as_str() {
        "linear" => LINEAR_TEMPLATE,
        "github" => GITHUB_TEMPLATE,
        "markdown" => MARKDOWN_TEMPLATE,
        other => {
            anyhow::bail!("unsupported tracker: '{other}'. Use 'linear', 'github', or 'markdown'.")
        }
    };

    std::fs::write(output_path, template)?;

    println!("Created {}", output_path.display());
    println!();
    println!("Next steps:");
    println!(
        "  1. Edit {} — fill in your project details",
        output_path.display()
    );
    if args.tracker != "markdown" {
        println!("  2. Set environment variables (e.g. LINEAR_API_KEY or GITHUB_TOKEN)");
    } else {
        println!("  2. Create issue .md files in your tasks/ directory");
    }
    println!("  3. Run: symphony validate {}", output_path.display());
    println!("  4. Run: symphony start {}", output_path.display());

    print_env_hint(&args.tracker, output_path);

    Ok(())
}

fn print_env_hint(tracker: &str, path: &Path) {
    println!();
    match tracker {
        "linear" => {
            println!("Required environment variables:");
            println!("  export LINEAR_API_KEY=lin_api_...");
            println!();
            println!("Quick test:");
            println!("  symphony run STI-123 --workflow-path {}", path.display());
        }
        "github" => {
            println!("Required environment variables:");
            println!("  export GITHUB_TOKEN=ghp_...");
            println!();
            println!("Quick test:");
            println!(
                "  symphony run 'owner/repo#42' --workflow-path {}",
                path.display()
            );
        }
        "markdown" => {
            println!("No environment variables required!");
            println!();
            println!("Create an issue file (e.g. tasks/task-001.md):");
            println!("  ---");
            println!("  id: TASK-001");
            println!("  title: My first task");
            println!("  state: Todo");
            println!("  priority: 1");
            println!("  labels: [feature]");
            println!("  ---");
            println!("  Description of the task.");
            println!();
            println!("Quick test:");
            println!("  symphony run TASK-001 --workflow-path {}", path.display());
        }
        _ => {}
    }
}
